yarnPath: .yarn/releases/yarn-3.2.1.cjs
npmScopes:
  progleasing:
    npmRegistryServer: https://art.api.progleasing.com/artifactory/api/npm/npm-aws-release/
    npmAuthIdent: ${ARTIFACTORY_ADMIN_AUTH_TOKEN}
    npmAlwaysAuth: true
